name: Run Nested Loop Script

on:
  push:
    branches:
      - main

jobs:
  run-nested-loop:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Run nested-loop.py script
      run: python cert-checker.py
